
identifier_name:
  allowed_symbols: "_"
  min_length: # only min_length
    error: 1 # only error
  excluded: # excluded via string array
    - id

  max_length:
    warning: 50
    error: 60

type_name:
    min_length: 3
    max_length:
        warning: 100
        error: 200
        
large_tuple:
    warning: 4
    error: 5

trailing_whitespace:
  ignores_empty_lines: true


opt_in_rules:
  - force_cast
  - force_unwrapping
  - force_try
  - array_init
  - closure_spacing
  - conditional_returns_on_newline
  - empty_string
  - empty_xctest_method
  - fallthrough
  - fatal_error_message
  - let_var_whitespace
  - literal_expression_end_indentation
  - multiline_parameters
  - nimble_operator
  - no_extension_access_modifier
  - pattern_matching_keywords

disabled_rules:
  - identifier_name
  - file_length
  - function_body_length
  - line_length
  - function_parameter_count
  - dynamic_inline
  - multiple_closures_with_trailing_closure
  - todo
  - legacy_constructor
  - type_body_length
  - cyclomatic_complexity
  - empty_xctest_method

excluded:
  - Pods
  - Frameworks
  - .git
